---
title: Geoff Boeing
author:
  name: Geoff Boeing
  email:
url: https://geoffboeing.com
baseurl:
description: >
  Geoff Boeing is an Associate Professor in USC's Department of Urban Planning
  and Spatial Analysis.

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: feed/

minima:
  skin: auto
  date_format: '%-d %b %Y'
  nav_pages:
    - index.md
    - _pages/cv.md
    - _pages/research.md
    - _pages/lab.md
    - _pages/media.md
    - _pages/contact.md
  show_excerpts: true
  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/gboeing
    - title: LinkedIn
      icon: linkedin
      url: https://linkedin.com/in/gboeing/
    - title: Bluesky
      icon: bluesky
      url: https://bsky.app/profile/geoffboeing.com
    - title: ORCID
      icon: orcid
      url: https://orcid.org/0000-0003-1851-6411
    - title: Google Scholar
      icon: google-scholar
      url: https://scholar.google.com/citations?user=xaKBPQQAAAAJ

google_analytics: G-DPXVKZK0K2

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
